### ISSUE TITLE
More information for the parts

### ISSUE THREAD

**Issue by TheNoim** [andrewsleigh/plotter#1]
Hi,

Currently, I try to recreate your project for a student project. However, I really have problems finding the correct parts. In your readme, you only gave limited information about each part which is a problem. If you try to get the parts on sites like aliexpress, then there are often too many options. For example:

> 30 or 40 tooth pulley for x-axis timing belt

[Kee Pang 1PC GT2 Timing Pulley](https://de.aliexpress.com/item/32900943510.html?spm=a2g0o.productlist.0.0.6b862827QPzkc1&algo_pvid=0e22f2bd-abc4-4c54-8bf3-ba5a5e17021f&algo_expid=0e22f2bd-abc4-4c54-8bf3-ba5a5e17021f-2&btsid=0b0a119a16017339844415167ec271&ws_ab_test=searchweb0_0,searchweb201602_,searchweb201603_ )

There too many possibilities. And I can not really wait until it arrives, because it just takes to long. The first order needs to be correct. Can you add a list of links? Even though if I don't buy there, at least I would have a complete spec list of each part with images. 

I hope you can help me. The project itself seems awesome.

**Comment by dunklesToast** [comment]
I've got the same problem :/

**Comment by andrewsleigh** [comment]
Hi - it's difficult to make a comprehensive parts list, partly cos I have no free time at the moment, (so maybe something crowd-sourced could help), but also because there is so much freedom in how each person chooses to make it. 

That being said, if you look these things up on Ooznest, which is a great UK supplier, they have a small range of the right stuff, and its easy to get a definitive component - you can always look elsewhere to find the equivalent.
